CrearMiPizza/CrearMiPizza/Models/DetallesIngredientesModel.cs
namespace CrearMiPizza.Models
{
    public class DetallesIngredientesModel
    {

        public string[] NombresIngredientes = new[] { "Jamón", "Hongos", "Salami", "Peperoni", "Pollo", "Carne molida", "Chorizo", "Tocino", "Queso parmesano", "Queso cheddar", "Cebolla", "Jalapeños" };
        public double[] PreciosIngredientes = new[] { 0.35, 0.17, 0.35, 0.35, 0.51, 0.17, 0.17, 0.85, 0.43, 0.43, 0.09, 0.09 };

        public string [] NombresSalsas = new[] { "Salsa de la casa","Salsa tomate artesanal", "Salsa barbacoa"};
        public double[] PrecioSalsas = new[] { 0.43,0.51,0.35};

        public string[] NombresMasas = new[] { "Original", "Orilla con queso", "Sartén" };
        public double[] PrecioMasas = new[] { 0.51, 0.94, 1.20 };

        public string[] Tamanios = new[] { "Personal (4 slides)", "Mediana (8 slides)", "Grande (16 slides)" };
        public int[] IncrementoPrecioXTamanio = new[] { 1, 2, 4};
    }
}

CrearMiPizza/CrearMiPizza/Models/PizzaModel.cs
using System.ComponentModel.DataAnnotations;

namespace CrearMiPizza.Models
{
    public class PizzaModel
    {
        public int [] IngredientesId { get; set; }
        public int Tamanio { get; set; }
        public int TipoSalsa { get; set; }
        public int TipoMasa { get; set; }

        [StringLength(30, MinimumLength = 1, ErrorMessage = "El nombre de la ciudad no puede superar los 30 caracteres")]
        [Required(ErrorMessage = "Es necesario que indique la ciudad de entrega")]
        [Display(Name = "Ingrese la ciudad de entrega")]
        public string CiudadEntrega { get; set; }

        [StringLength(100, MinimumLength = 1, ErrorMessage = "La dirección no puede superar los 100 caracteres")]
        [Required (ErrorMessage ="Es necesario que indique la dirección de entrega")]
        [Display(Name = "Ingrese la dirección de entrega")]
        public string DireccionEntrega { get; set; }

        [StringLength(30, MinimumLength = 1, ErrorMessage = "El nombre completo no puede superar los 30 caracteres")]
        [Required(ErrorMessage = "Es necesario que indique su nombre")]
        [Display(Name ="Ingrese su nombre completo")]
        public string NombreDuenioPizza { get; set;}

        [StringLength(8, MinimumLength = 8,ErrorMessage ="El número de teléfono debe tener 8 digitos")]
        [RegularExpression("^[0-9]*$",ErrorMessage = "El formato de ingreso es Ej: 22334455")]
        [Required(ErrorMessage = "Es necesario que indique su número de teléfono")]
        [Display(Name = "Ingrese su número de teléfono")]
        public string TelefonoEntrega {get; set;}
    }
}

CrearMiPizza/CrearMiPizza/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CrearMiPizza.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CrearMiPizza/CrearMiPizza/Controllers/PizzaController.cs
using System.Web.Mvc;
using CrearMiPizza.Models;
using CrearMiPizza.Servicios;

namespace CrearMiPizza.Controllers
{
    public class PizzaController : Controller
    {
        public ActionResult CrearPizza()
        {
            ViewBag.detallesIngredientes = new DetallesIngredientesModel();
            ViewBag.Message = "";
            if (TempData["Message"]!=null) {
                ViewBag.Message = TempData["Message"].ToString();
            }
            return View();
        }
        [HttpPost]
        public ActionResult GenerarInformePedido(PizzaModel pizza) {
            if (pizza != null && ModelState.IsValid)
            {
                CalculadoraPrecios calculadora = new CalculadoraPrecios(pizza);
                ViewBag.detallesIngredientes = new DetallesIngredientesModel();
                ViewBag.precioFinalPizza = calculadora.CalcularPrecioTotalPizza();
                return View(pizza);
            }
            else {
                @TempData["Message"] = "Algo salió mal vuelva a efectuar su pedido";
                return RedirectToAction("CrearPizza");
            }
            
        }
    }
}

CrearMiPizza/CrearMiPizza/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Página de inicio";
}

<html>

<head>



</head>

<body class="body-content" id="body-inicio">

    <div class="jumbotron">
        <h1>PIZZA PERSONALIZADA</h1>
        <p class="lead">Cree su pizza con sus ingredientes favoritos y se la enviamos hasta su casa  </p>
        <div class="text-md-center">
            <img src="~/Content/img/pizzabanner.jpg" alt="" loading="lazy" id="img-inicio">
        </div>
        <hr />
        <p><a href="/Pizza/CrearPizza" class="btn btn-primary btn-lg "> Crear mi pizza </a></p>
        <p> Aproveche nuestros envíos gratis de temporada </p>
    </div>

</body>


</html>

CrearMiPizza/CrearMiPizza/Views/Pizza/CrearPizza.cshtml
@model CrearMiPizza.Models.PizzaModel


@{
    ViewBag.Title = "Crear mi pizza";
    var detallesIngresientes = ViewBag.detallesIngredientes;
}


<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="~/Content/estilos.css" />
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/main.js"></script>

</head>

<body class="body-content" >

    <hr />
    <h2> <strong> ¡Elija los elementos favoritos para su pizza y aproveche el envío gratis por temporada!</strong></h2>
    <hr />

    @if (ViewBag.Message != "") {
        <div class="alert-danger">
            @ViewBag.Message
        </div>
    }

    <div class="wrap">
        <ul class="tabs">
            <li><a href="#tab1"><span class="fas fa-ruler"></span><span class="tab-text"> Tamaño </span></a></li>
            <li><a href="#tab2"><span class="fas fa-bread-slice"></span><span class="tab-text"> Masa y salsa </span></a></li>
            <li><a href="#tab3"><span class="fas fa-pizza-slice"></span><span class="tab-text"> Ingredientes </span></a></li>
            <li><a href="#tab4"><span class="fas fa-paper-plane"></span><span class="tab-text"> Datos de envío </span></a></li>

        </ul>

        <div class="secciones">
            @using (Html.BeginForm("GenerarInformePedido", "Pizza", FormMethod.Post, new { @id = "formPreg", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <article id="tab1">

                    <div class="row">
                        <div class="col-md-6">
                            <hr />
                            <h3>Elige el tamaño de la pizza</h3>
                            <hr />

                            <div class="form-group">
                                @for (int i = 0; i < detallesIngresientes.Tamanios.Length; ++i)
                                {
                                    string valorIndice = i.ToString();
                                    @Html.RadioButtonFor(model => model.Tamanio, valorIndice, new { @checked = "true" }) <spam class="tamanios-letras-rb"> @detallesIngresientes.Tamanios[i] </spam> <hr />
                                }

                                <a href="#tab2" class="btn btn-primary btn-lg" id="pasarTab1-Tab2"> Siguiente </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="center">
                                <img src="~/Content/img/pizzatamanios.jpg" width="280" height="280" />
                            </div>
                        </div>
                    </div>
                </article>

                <article id="tab2">
                    <div class="row">
                        <div class="col-md-4">
                            <h4>Seleccione la masa de su preferencia</h4>
                            <hr />
                            @for (int i = 0; i < detallesIngresientes.NombresMasas.Length; ++i)
                            {
                                string valorIndice = i.ToString();
                                @Html.RadioButtonFor(model => model.TipoMasa, valorIndice, new { @checked = "true" }) <spam class="tamanios-letras-rb"> @detallesIngresientes.NombresMasas[i] </spam> <hr />
                            }
                        </div>
                        <div class="col-md-4">
                            <h4>Seleccione la salsa de su preferencia</h4>
                            <hr />
                            @for (int i = 0; i < detallesIngresientes.NombresSalsas.Length; ++i)
                            {
                                string valorIndice = i.ToString();
                                @Html.RadioButtonFor(model => model.TipoSalsa, valorIndice, new { @checked = "true" }) <spam class="tamanios-letras-rb"> @detallesIngresientes.NombresSalsas[i] </spam> <hr />
                            }
                        </div>
                        <div class="col-md-4">
                            <hr />
                            <img src="~/Content/img/salsamasa.jpg" width="300" height="200" />
                            <hr />
                            <a href="#tab3" class="btn btn-primary btn-lg" id="pasarTab2-Tab3"> Siguiente </a>
                        </div>
                    </div>
                </article>

                <article id="tab3">

                    <h3>Elige los ingredientes de la pizza</h3>
                    <hr />

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <img src="~/Content/img/ingresientes1.jpg" width="330" height="200" /> <hr />
                                @for (int i = 0; i < 4; ++i)
                                {
                                    string valorIndice = i.ToString();
                                    <input name="IngredientesId" type="checkbox" class="misCheckBox" value=@valorIndice /> @detallesIngresientes.NombresIngredientes[i];
                                    <br />
                                }
                                <hr />
                                <a href="#tab4" class="btn btn-primary btn-lg" id="pasarTab3-Tab4"> Siguiente </a>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <img src="~/Content/img/ingresientes2.jpg" width="330" height="200" /> <hr />
                                @for (int i = 4; i < 8; ++i)
                                {
                                    string valorIndice = i.ToString();
                                    <input name="IngredientesId" type="checkbox" class="misCheckBox" value=@valorIndice /> @detallesIngresientes.NombresIngredientes[i];
                                    <br />
                                }

                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <img src="~/Content/img/ingresientes3.jpg" width="330" height="200" /> <hr />
                                @for (int i = 8; i < 12; ++i)
                                {
                                    string valorIndice = i.ToString();
                                    <input name="IngredientesId" type="checkbox" class="misCheckBox" value=@valorIndice /> @detallesIngresientes.NombresIngredientes[i];
                                    <br />
                                }
                                <hr />
                                <input type="checkbox" id="selectAll" onClick="toggle(this)" /> Seleccionar todos
                                <hr />
                            </div>
                        </div>
                    </div>
                </article>

                <article id="tab4">
                    <div class="form-group">

                        <div id="center">
                            <h3>Formulario de envío</h3>

                            @Html.LabelFor(model => model.NombreDuenioPizza)
                            @Html.TextBoxFor(model => model.NombreDuenioPizza, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.NombreDuenioPizza, "", new { @class = "text-danger" })

                            <hr />

                            @Html.LabelFor(model => model.TelefonoEntrega)
                            @Html.TextBoxFor(model => model.TelefonoEntrega, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TelefonoEntrega, "", new { @class = "text-danger" })

                            <hr />

                            @Html.LabelFor(model => model.CiudadEntrega)
                            @Html.TextBoxFor(model => model.CiudadEntrega, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CiudadEntrega, "", new { @class = "text-danger" })

                            <hr />

                            @Html.LabelFor(model => model.DireccionEntrega)
                            @Html.TextBoxFor(model => model.DireccionEntrega, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DireccionEntrega, "", new { @class = "text-danger" })

                            <hr />
                            <input type="submit" value="Confirmar mi pedido" class="btn btn-success" />
                        </div>
                    </div>
                </article>
            }
        </div>
    </div>
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

</html>

CrearMiPizza/CrearMiPizza/Views/Pizza/EnviaDatosCreacion.cshtml
@{
    ViewBag.Title = "Detalles de mi pizza";
    var pizzaCreada = Model;
    var detallesIngresientes = ViewBag.detallesIngredientes;
}


<html>

<head>
    <link rel="stylesheet" type="text/css" href="~/Content/estilos.css" />
   
</head>

<body class="body-content" id="body-inicio">
    <hr />
    <div class="jumbotron" id="center">
        <div class="text-center">
            <h1>Detalles de la entrega</h1>
            <hr />
            <h7> <strong>Nombre del cliente:</strong> @pizzaCreada.NombreDuenioPizza  </h7> <br />
            <h7> <strong>Teléfono del cliente: </strong> @pizzaCreada.TelefonoEntrega  </h7> <br />
            <h7> <strong> Ciudad de entrega:</strong> @pizzaCreada.CiudadEntrega  </h7> <br />
            <h7> <strong> Dirección de entrega:</strong> </h7> <br />
            <p>
                @pizzaCreada.DireccionEntrega
            </p>
            <hr />
        </div>

        <div class="text-center">
            <h1>Detalles de la pizza</h1>
            <hr />
        </div>
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th scope="col"> - </th>
                    <th scope="col"> Tamaño de la pizza </th>
                    <th scope="col"> Aumento de precio </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row"> * </th>
                    <td> @detallesIngresientes.Tamanios[pizzaCreada.Tamanio]  </td>
                    <td> x @detallesIngresientes.IncrementoPrecioXTamanio[pizzaCreada.Tamanio] </td>
                </tr>
            </tbody>
        </table>

        <table class="table table-borderless">
            <thead>
                <tr>
                    <th scope="col">- </th>
                    <th scope="col">Tipo de salsa </th>
                    <th scope="col">Precio (colones) </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row"> * </th>
                    <td> @detallesIngresientes.NombresSalsas[pizzaCreada.Tamanio]  </td>
                    <td> @detallesIngresientes.PrecioSalsas[pizzaCreada.Tamanio] </td>
                </tr>
            </tbody>
        </table>

        <table class="table table-borderless">
            <thead>
                <tr>
                    <th scope="col">- </th>
                    <th scope="col">Tipo de masa  </th>
                    <th scope="col">Precio (colones) </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row"> * </th>
                    <td> @detallesIngresientes.NombresMasas[pizzaCreada.Tamanio]  </td>
                    <td> @detallesIngresientes.PrecioMasas[pizzaCreada.Tamanio] </td>
                </tr>
            </tbody>
        </table>
        <hr />
        <div class="text-center">
            <h1>Ingredientes de la pizza</h1>
            <hr />
        </div>

        @if (pizzaCreada.IngredientesId != null)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Ingrediente</th>
                        <th scope="col">Precio (colones)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var number in pizzaCreada.IngredientesId)
                    {
                        <tr>
                            <th scope="row"> @(number + 1)</th>
                            <td>@detallesIngresientes.NombresIngredientes[number]</td>
                            <td>@detallesIngresientes.PreciosIngredientes[number]</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="text-center">
                <h7>Usted no seleccionó ingredientes</h7>
            </div>
        }
        <div class="text-center">
            <hr />
            <h1>Monto total por cancelar</h1>
            <hr />
            <div class="text-center text-danger"><h4><strong>99999</strong></h4></div>
        </div>

        <div class="text-center">
            <hr />
            <a class="btn btn-success" id="termina-pedido"> <spam class="txt-btn"> Terminar mi pedido </spam> </a>
            <a class="btn btn-danger" id="cancelar-pedido">  <spam class="txt-btn"> Cancelar mi pedido </spam> </a>
        </div>

    </div>

    <div>

        <div id="vtn-modal-irInicio" class="modal">
            <!-- Contenido -->
            <div class="modal-content">
                <div class="text-center">
                    <h4 class="alert-success"> Su orden está en camino, gracias por preferirnos </h4>
                    <a class="btn btn-success" href="/Home/Index"> <spam class="txt-btn"> Aceptar </spam> </a>
                </div>
            </div>

        </div>

        <div id="vtn-modal-anularPedido" class="modal">
            <!-- Contenido -->
            <div class="modal-content">
                <span class="close">&times;</span>
                <div class="text-center">
                    <h4 class="alert-danger"> ¿Está seguro que quiere cancelar su pedido? </h4>
                    <a class="btn btn-success" href="/Home/Index"> <spam class="txt-btn"> Sí </spam> </a>
                    <a class="btn btn-danger" id="btn-no"> <spam class="txt-btn"> No </spam> </a>
                </div>
            </div>

        </div>

    </div>
    <script src="~/Scripts/ventana.js"></script>
</body>

</html>

CrearMiPizza/CrearMiPizza/Views/Pizza/GenerarInformePedido.cshtml
@{
    ViewBag.Title = "Detalles de mi pizza";
    var pizzaCreada = Model;
    var detallesIngresientes = ViewBag.detallesIngredientes;
}


<html>

<head>
    <link rel="stylesheet" type="text/css" href="~/Content/estilos.css" />
   
</head>

<body class="body-content" id="body-inicio">
    <hr />
    <div class="jumbotron" id="center">
        <div class="text-center">
            <h1>Detalles de la entrega</h1>
            <hr />
            <h7> <strong>Nombre del cliente:</strong> @pizzaCreada.NombreDuenioPizza  </h7> <br />
            <h7> <strong>Teléfono del cliente: </strong> @pizzaCreada.TelefonoEntrega  </h7> <br />
            <h7> <strong> Ciudad de entrega:</strong> @pizzaCreada.CiudadEntrega  </h7> <br />
            <h7> <strong> Dirección de entrega:</strong> </h7> <br />
            <p>
                @pizzaCreada.DireccionEntrega
            </p>
            <hr />
        </div>

        <hr />
        <div class="text-center">
            <h1>Ingredientes de la pizza</h1>
            <hr />
        </div>

        @if (pizzaCreada.IngredientesId != null)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Ingrediente</th>
                        <th scope="col">Precio </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var number in pizzaCreada.IngredientesId)
                    {
                        <tr>
                            <th scope="row"> @(number + 1)</th>
                            <td>@detallesIngresientes.NombresIngredientes[number]</td>
                            <td>$ @detallesIngresientes.PreciosIngredientes[number]</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="text-center">
                <h7>Usted no seleccionó ingredientes</h7>
            </div>
        }
        <hr />
        <div class="text-center">
            <h1>Detalles de la pizza</h1>
            <hr />
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"> - </th>
                    <th scope="col">Característica </th>
                    <th scope="col">Precio </th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <th scope="row"> * </th>
                    <td>Masa: @detallesIngresientes.NombresMasas[pizzaCreada.TipoMasa]  </td>
                    <td>$ @detallesIngresientes.PrecioMasas[pizzaCreada.TipoMasa] </td>
                </tr>

                <tr>
                    <th scope="row"> * </th>
                    <td>Salsa: @detallesIngresientes.NombresSalsas[pizzaCreada.TipoSalsa]  </td>
                    <td>$ @detallesIngresientes.PrecioSalsas[pizzaCreada.TipoSalsa] </td>
                </tr>

                <tr>
                    <th scope="row"> * </th>
                    <td>Tamaño: @detallesIngresientes.Tamanios[pizzaCreada.Tamanio]  </td>
                    <td>Total x @detallesIngresientes.IncrementoPrecioXTamanio[pizzaCreada.Tamanio] </td>
                </tr>
            </tbody>
        </table>

        <div class="text-center">
            <hr />
            <h1>Precio de la pizza</h1>
            <hr />
            <div class="text-center text-danger"><h4><strong> $ @(((ViewBag.precioFinalPizza/ detallesIngresientes.IncrementoPrecioXTamanio[pizzaCreada.Tamanio]))/1.13) </strong></h4></div>
            <div class="text-center text-danger"> No incluye iva 13% ni aumento por tamaño </div>
        </div>

        <div class="text-center">
            <hr />
            <h1>Monto total por pagar</h1>
            <hr />
            <div class="text-center text-danger"><h4><strong> $ @ViewBag.precioFinalPizza </strong></h4></div>
            <div class="text-center text-danger"> (iva 13% incluido) </div>
        </div>

        <div class="text-center">
            <hr />
            <a class="btn btn-success" id="termina-pedido"> <spam class="txt-btn"> Terminar mi pedido </spam> </a>
            <a class="btn btn-danger" id="cancelar-pedido">  <spam class="txt-btn"> Cancelar mi pedido </spam> </a>
        </div>

    </div>

    <div>

        <div id="vtn-modal-irInicio" class="modal">
            <!-- Contenido -->
            <div class="modal-content">
                <div class="text-center">
                    <h4 class="alert-success"> @pizzaCreada.NombreDuenioPizza su orden está en camino, gracias por preferirnos </h4>
                    <a class="btn btn-success" href="/Home/Index"> <spam class="txt-btn"> Aceptar </spam> </a>
                </div>
            </div>

        </div>

        <div id="vtn-modal-anularPedido" class="modal">
            <!-- Contenido -->
            <div class="modal-content">
                <span class="close">&times;</span>
                <div class="text-center">
                    <h4 class="alert-danger"> ¿Está seguro que quiere cancelar su pedido? </h4>
                    <a class="btn btn-success" href="/Home/Index"> <spam class="txt-btn"> Sí </spam> </a>
                    <a class="btn btn-danger" id="btn-no"> <spam class="txt-btn"> No </spam> </a>
                </div>
            </div>

        </div>

    </div>
    <script src="~/Scripts/ventana.js"></script>
</body>
</html>

CrearMiPizza/CrearMiPizza/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet">

    <title>@ViewBag.Title - Pizza personalizada</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>



    <nav class="navbar fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="/Home/Index">
            <img src="~/Content/img/imgicon.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
            Pizza personalizada
        </a>
    </nav>


    <div class="container body-content" id="div-footer">
        @RenderBody()
        <hr />
        <footer class="page-footer font-small unique-color-dark pt-4" id="mi-footer">

            <!-- Footer Elements -->
            <div class="container">

                <!-- Call to action -->
                <ul class="list-unstyled list-inline text-center py-2">
                    <li class="list-inline-item">
                        <p> ¡La mejor pizza personalizada hasta su casa! </p>
                    </li>

                </ul>
                <!-- Call to action -->

            </div>
            <!-- Footer Elements -->
            <!-- Copyright -->
            <div class="footer-copyright text-center py-3">
                <p>&copy; @DateTime.Now.Year - Pizza personalizada</p>
                <p>Edwin Josué Brenes Cambronero, B51187</p>
            </div>
            <!-- Copyright -->

        </footer>
    </div>


</body>
</html>